In [1]:
import numpy as np

In [5]:
# Prepare Graph
g1 = np.array(
    [
        [1, 2, 3, 4],
        [2, 1, 0, 0],
        [3, 0, 1, 2],
        [4, 0, 2, 1],
    ]
)
print("g1 shape:", g1.shape)



g1 shape: (4, 4)


In [11]:
a = np.random.randint(0, 2+1, size=(40, 40))
m = np.tril(a) + np.tril(a, -1).T
print(m)

[[2 1 1 ... 0 2 1]
 [1 0 0 ... 0 2 1]
 [1 0 0 ... 2 2 2]
 ...
 [0 0 2 ... 0 2 1]
 [2 2 2 ... 2 2 2]
 [1 1 2 ... 1 2 2]]
