In [1]:
import numpy as np

In [3]:
x = np.array([i for i in range(9)]).reshape((3, 3))

idx = 1

y = x[idx, [True if i != idx else False for i in range(3)]]

In [5]:
print(x, y)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [4 3 4]
